server:
  port: 8089
  servlet:
    contextPath: /server
spring:
  application:
    name: Springen application
  # h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    sql-script-encoding: UTF-8
    initialization-mode: always
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      nameing:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        
  # mysql
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/findARoommate?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
#    username: root
#    password: root
#    sql-script-encoding: UTF-8
#    initialization-mode: always
#    tomcat:
#      test-while-idle: true
#      validation-query: SELECT 1
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#      nameing:
#        strategy: org.hibernate.cfg.ImprovedNamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect